# This file contains values from Cookiecutter

default_context:
  project_name: "valorant_api"
  project_description: "Valorant API Wrapper for https://github.com/Henrik-3/unofficial-valorant-api"
  organization: "Manuel Raimann"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "Manuel Raimann"
  email: "raimannma@outlook.de"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
